import = [
    "~/.config/alacritty/bamboo.toml"
]

[env]
term = "xterm-256color"

[window]
opacity = 0.95
blur = false
decorations = "none"
padding = { x = 0, y = 0 }

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11.0
builtin_box_drawing = true
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
bindings = [ { mouse = "Right", mods = "Control", action = "Paste" }, ]

[keyboard]
bindings = [
    { key = "A", mods = "Control|Shift", chars = "tmux-sm\n" },
    { key = "F", mods = "Control|Shift", chars = "tmux-sessionizer\n" },
]
