import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
term = "xterm-256color"

[window]
opacity = 1
blur = true
decorations = "none"
startup_mode = "Windowed"
dynamic_padding = true
padding = { x = 6, y = 0 }

[cursor]
style = "Beam"

[font]
size = 11.0
builtin_box_drawing = true
normal = { family = "Monaspace Argon", style = "Regular" }
bold = { family = "Monaspace Argon", style = "Bold" }
italic = { family = "Monaspace Argon", style = "Italic" }
bold_italic = { family = "Monaspace Argon", style = "Bold Italic" }

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
bindings = [ { mouse = "Right", mods = "Control", action = "Paste" }, ]

[keyboard]
bindings = [
    { key = "A", mods = "Control|Shift", chars = "tmux-sm\n" },
]
