[general]
import = ["~/.config/alacritty/kanagawa_dragon.toml"]

[env]
term = "xterm-256color"

[window]
opacity = 1.0
blur = false
decorations = "none"
padding = { x = 0, y = 0 }

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0
builtin_box_drawing = false
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]
