---
keys:
  - &host_jupiter age1glelmjynysv38av0vrm9de2shzd909utxqpzkqg8v22lp4jxvamqgksykp
  - &host_luna age150rcj355hegl9n2l9t3v2ukdtvnzt3uc09c8kngzzq2y2r3p2vkqwdy9v0
  - &host_rpi4 age197zuvurk9jxcyakv733uqx04pk34hs36yd0awdcyv6d7dmrg397qefjmq7
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *host_jupiter
          - *host_luna
          - *host_rpi4
