keys:
  - &jupiter age1glelmjynysv38av0vrm9de2shzd909utxqpzkqg8v22lp4jxvamqgksykp
  - &luna age150rcj355hegl9n2l9t3v2ukdtvnzt3uc09c8kngzzq2y2r3p2vkqwdy9v0
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *jupiter
          - *luna
