path=(
  $HOME/.local/bin
  /var/lib/flatpak/exports/bin
  $HOME/.cargo/bin
  $HOME/go/bin
  /usr/local/bin/go/bin
  $HOME/.node_modules/bin
  $path)

# Runtime environment variables
export ZDOTDIR=$HOME/.config/zsh
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export EDITOR="nvim"
export VISUAL="nvim"
export MANPAGER='nvim --clean +Man!'
export npm_config_prefix="$HOME/.node_modules/"
