{
  imports = [
    ./adguard.nix
    ./amd-gpu.nix
    ./bluetooth.nix
    ./btrfs.nix
    ./docker.nix
    ./firewall.nix
    ./flatpak.nix
    ./gaming.nix
    ./libvirt.nix
    ./node_exporter.nix
    ./openssh.nix
    ./podman.nix
    ./power-profiles-daemon.nix
    ./smb-mount.nix
    ./sysctl-hardening.nix
    ./tailscale.nix
    ./vagrant.nix
    ./zram.nix
  ];
}
