---
name: "build"
"on":
  push:
    branches:
      - "main"
    paths:
      - "flake.lock"

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        machine:
          - host: jupiter
          - host: luna
          - host: attic

    steps:
      - name: Free up some space on the runner to avoid out-of-space errors
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Connect to the Tailscale network
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - uses: actions/checkout@v4

      - run: |
          sudo mkdir -p /etc/nix
          echo -e "machine https://nixcache.chrizer.xyz\npassword ${{ secrets.ATTIC_TOKEN }}" | sudo tee /etc/nix/netrc > /dev/null

      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            substituters = https://nixcache.chrizer.xyz/system?priority=41 https://cache.nixos.org/
            trusted-public-keys = system:GT8qDFyehp/zpWF5AuB5LMyAzaR5dgQDqpKxm9KAnJE= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - run: |
          nix run github:zhaofengli/attic#default login cache https://nixcache.chrizer.xyz ${{ secrets.ATTIC_TOKEN }}
          nix run github:zhaofengli/attic#default use system

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build and push system configurations
        run: |
          nix build .#nixosConfigurations.${{ matrix.machine.host }}.config.system.build.toplevel
          nix run github:zhaofengli/attic#default push system result
