---
name: "build"
"on":
  push:
    branches:
      - "main"
    paths:
      - "flake.lock"
  # Allow running the workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        toBuild:
          - system: .#nixosConfigurations.jupiter.config.system.build.toplevel
          - system: .#nixosConfigurations.luna.config.system.build.toplevel
          - system: .#iso
          - home: chzerv@luna
          - home: chzerv@jupiter

    steps:
      - name: Free up some space on the runner to avoid out-of-space errors
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Clone this repository
        uses: actions/checkout@v4

      - name: Set up cachix
        uses: cachix/cachix-action@master
        with:
          name: chzerv
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: result

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Ensure /etc/sops/age/keys.txt exists, even if it is empty
        run: |
          sudo mkdir -p /etc/sops/age
          sudo touch /etc/sops/age/keys.txt

      - name: Build and push system configurations and ISO
        run: nix build --impure ${{ matrix.toBuild.system }} | cachix push chzerv

      - name: Build and push home-manager configurations
        run: nix-shell -p home-manager --run 'home-manager build --flake .#${{ matrix.toBuild.home }}' | cachix push chzerv
